# vim: set sw=2 sts=2 si:
---
- hosts: 10.117.142.34
  gather_facts: false
  vars:
    users: 
    - jong852
  tasks:
    - name: Add user to Linux system
      user:
        name: "{{ item }}"
        home: /home/{{ item }}
        groups: syslogmgt
        append: yes
      with_items: "{{ users }}"
      become: true

    - name: Create SSH directory
      file:
        path: "/home/{{ item }}/.ssh"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0700
        state: directory
      with_items: "{{ users }}"
      become: true

    - name: Create empty file (authorized_keys)
      file:
        path: "/home/{{ item }}/.ssh/authorized_keys"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0600
        state: touch
      with_items: "{{ users }}"
      become: true

    - name: Deploy public key
      lineinfile:
        path: "/home/{{ item }}/.ssh/authorized_keys"
        line: "{{ pubkey }}"
      with_items: "{{ users }}"
      become: true
